spring:
  ai:
    openai:
      api-key: sk-f187434d640b4c98858124d46d0342de
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
server:
  8080
logging:
  level:
    org.springframework.ai: DEBUG
